### ISSUE TITLE
Passing string, returns it inside array

### ISSUE THREAD

**Issue by dopesong** [slimphp/Slim-Flash#24] opened 2016-08-13 12:38 UTC
@geggleto said he will fix what he broke 💃 

https://github.com/slimphp/Slim-Flash/commit/5bd5f75eac27433beeccd60d2777b4e58da84834#diff-8b1b6164c747942bdb2576f146cf4e5eR87

**Comment by akrabat** [comment] 2016-11-11 19:28
As this change came in as PR #1 and was merged by Josh, I think it's unlikely to change.

**Comment by dopesong** [comment] 2016-11-11 19:31
Maybe @codeguy missed something. @codeguy any thoughts on this?

**Comment by jkrehm** [comment] 2017-04-10 18:10
I just ran into this, too. I'm curious why all flashed values are forced into an array when that's just one use case among many.

**Comment by krotovic** [comment] 2017-05-24 07:29
I have created new pull request that should resolve this. It returns array only if you add more than one message under the same key.

**Comment by MrSam** [comment] 2017-06-08 11:01
Hmm not sure if that would be expected behaviour. When using type hinting in PHP7.x it should always return the same type, in this case array.

When expecting a single string https://github.com/slimphp/Slim-Flash/issues/29 could be used.

**Comment by krotovic** [comment] 2017-06-13 09:51
Hmm, @MrSam your solution may be better... Until it's available I will have a fork of this repository with my solution implemented and it will be published on Packagist as `krotovic/slim-flash` so fell free to use it. 

I needed it immediately in my project, so please don't consider my actions being rude. I might have only wrap this library but I wasn't thinking about it much and since there are others requesting this feature, this solution might get handy.

**Comment by akrabat** [comment] 2017-10-22 10:09
Closed #33

**Closed as completed by akrabat** 2017-10-22 10:09 UTC
